#!/bin/bash

# Script to retrieve a file via FTP

FTP_SERVER=ftp.nl.debian.org
FTP_PATH=/debian/dists/jessie/main/installer-amd64/20150422/images/cdrom
REMOTE_FILE=debian-cd_info.tar.gz

ftp -n <<- _EOF_
         open $FTP_SERVER
         user anonymous earodriguez@earodriguez-tp450
         cd $FTP_PATH
         hash
         get $REMOTE_FILE
         bye
         _EOF_

ls -l $REMOTE_FILE